// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.1 (Build Build 162 10/23/2013)
// Created on Fri Mar 23 01:41:54 2018

RamanScheme RamanScheme_inst
(
	.enable(enable_sig) ,	// input  enable_sig
	.clk(clk_sig) ,	// input  clk_sig
	.data(data_sig) ,	// input [11:0] data_sig
	.ratio1(ratio1_sig) ,	// output [12*POINTS-1:0] ratio1_sig
	.ratio2(ratio2_sig) ,	// output [12*POINTS-1:0] ratio2_sig
	.ratio3(ratio3_sig) ,	// output [12*POINTS-1:0] ratio3_sig
	.ratio8(ratio8_sig) ,	// output [12*POINTS-1:0] ratio8_sig
	.ratio9(ratio9_sig) ,	// output [12*POINTS-1:0] ratio9_sig
	.ratio10(ratio10_sig) 	// output [12*POINTS-1:0] ratio10_sig
);

